### ISSUE TITLE
help

### ISSUE THREAD

**Issue by nekef** [Hotroos/Survival#1]
**Bold**
*italic*
~~mistake~~
*** important***
<sub>tiny middle</sub>
<sup>help</sup>

**Comment by Hotroos** [comment]
Why

**Comment by nekef** [comment]
```
# this is a comment in python
```

**_python_**

[youtube.com](youtube.com)

![image](https://github.com/Hotroos/Survival/assets/151402781/33f20396-dac0-421d-ab4e-077f1487a3fe)

@Hotroos 

- [ hello] - Hello

#Python
> He'll python

`hi`
